---
- name: Installing stow
  apt: name=stow

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:matthieurobert/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    version: main

- name: Stow dotfiles
  shell: cd $HOME/dotfiles && ./ubuntu
    
